import {
  LayoutDashboard,
  ScanLine,
  Bot,
  Tractor,
  ClipboardCheck,
  BookOpen,
  Bell,
  UserCircle,
  Settings,
  LogOut,
  ChevronDown,
  Leaf,
  QrCode,
  LineChart,
  Thermometer,
  Droplets,
  Sprout,
  Package,
  Store,
  Home,
  AlertTriangle,
  FileText,
  Download,
  Info,
  Video,
  CheckSquare,
  Warehouse,
  ListChecks,
  Truck,
  Apple,
  ShieldCheck,
  Waypoints,
  FlaskConical,
  MapPin,
  CalendarDays,
  Trees,
  FlaskRound,
} from 'lucide-react';

export const Icons = {
  logo: Leaf,
  dashboard: LayoutDashboard,
  scan: ScanLine,
  aiAssistant: Bot,
  farmManagement: Tractor,
  compliance: ClipboardCheck,
  education: BookOpen,
  notifications: Bell,
  user: UserCircle,
  settings: Settings,
  logout: LogOut,
  chevronDown: ChevronDown,
  qrCode: QrCode,
  lineChart: LineChart,
  temperature: Thermometer,
  humidity: Droplets,
  soilMoisture: Sprout, // Using Sprout as a proxy for soil moisture
  package: Package,
  store: Store,
  home: Home,
  alert: AlertTriangle,
  report: FileText,
  download: Download,
  info: Info,
  video: Video,
  checklist: CheckSquare,
  warehouse: Warehouse,
  audit: ListChecks,
  transport: Truck,
  product: Apple, // Generic product
  foodSafety: ShieldCheck,
  timeline: Waypoints,
  pesticide: FlaskConical, // Representing chemicals
  fertilizer: FlaskRound, // Representing chemicals
  location: MapPin,
  date: CalendarDays,
  crop: Trees,
};

export type IconName = keyof typeof Icons;
